DNANexus docs
gymrek-lab/gymreklab.github.io pull request #4
Opened 2023-03-16 17:24 UTC by LiterallyUniqueLogin

2023-03-16 17:50 UTC, aryarm commented on doc/DNANexus.rst
> +#. Sign up `here <https://bbams.ndph.ox.ac.uk/ams/resProjects>`_
these bullets might show up a bit strangely?
![image](https://user-images.githubusercontent.com/23412689/225708471-a39b423c-a870-44c4-b882-3793dd609228.png)

2023-03-16 18:06 UTC, aryarm requested changes
there were a few warnings that came up when the system tried to build the docs
I think these suggestions I made should fix them

also, I think you need to add the new `DNANexus.rst` to the table of contents in `index.rst`?

2023-03-16 18:06 UTC, aryarm commented on doc/DNANexus.rst
> +The link `here <https://dnanexus.gitbook.io/uk-biobank-rap/working-on-the-research-analysis-platform/billing-and-costs#rates>`_
Try this to resolve the build failures
```suggestion
The link `here <https://dnanexus.gitbook.io/uk-biobank-rap/working-on-the-research-analysis-platform/billing-and-costs#rates>`__
```

2023-03-16 18:06 UTC, aryarm commented on doc/DNANexus.rst
> +#. Sign up `here <https://bbams.ndph.ox.ac.uk/ams/resProjects>`_
Try this to resolve the build failures
```suggestion
#. Sign up `here <https://bbams.ndph.ox.ac.uk/ams/resProjects>`__
```

2023-03-16 19:10 UTC, aryarm commented on doc/DNANexus.rst
> +#. Sign up `here <https://bbams.ndph.ox.ac.uk/ams/resProjects>`_
ah, I just meant that the numbers are all 1

Should they be 1, 2, 3, etc?

2023-03-17 04:01 UTC, aryarm approved these changes

2023-03-17 04:05 UTC, aryarm commented
looks like it's good to go!

2023-03-17 04:33 UTC, yli091230 approved these changes

2023-03-17 04:34 UTC, yli091230 commented
@aryarm Thanks for helping with the review!

2023-03-28 03:07 UTC, merged